Copy Debug

diff --git a/Day-7/strapi/dockerfile b/Day-7/strapi/dockerfile
--- a/Day-7/strapi/dockerfile
+++ b/Day-7/strapi/dockerfile
@@ -14,6 +14,8 @@ ENV DATABASE_PASSWORD=password
 #--------Copying Local App directory--------------
 WORKDIR /strapi/
 RUN echo "== Checking build context ==" && ls -al && ls -al ./test-strapi || echo "test-strapi not found"
+RUN echo "Build context contents:" && ls -al && ls -al ./strapi/test-strapi || echo "strapi/test-strapi not found"
+
 COPY ./test-strapi/ /strapi/
 
 #--------Installing dependencies--------------
