Docker Copy debug

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -19,6 +19,11 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Show contents
+        run: |
+          ls -al Day-7/strapi
+          ls -al Day-7/strapi/test-strapi || echo "test-strapi missing"
+
       - name: Set up Docker
         uses: docker/setup-buildx-action@v3
 
@@ -33,7 +38,6 @@ jobs:
         run: |
           TAG="strapi-v${GITHUB_RUN_NUMBER}"
           echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
-          # echo "$TAG" > image_tag.txt
 
       - name: Build and push Docker image
         working-directory: Day-7/strapi
